GET http://127.0.0.1:8000/charts/column_count/?column=address&model=vacancies
Accept: application/json

###

GET http://127.0.0.1:8000/charts/column_count/?column=skills&model=vacancies
Accept: application/json

###

GET http://127.0.0.1:8000/charts/column_count/?column=published_at&model=vacancies
Accept: application/json

###

GET http://127.0.0.1:8000/charts/column_count/?column=area&model=resume
Accept: application/json

###

GET http://127.0.0.1:8000/charts/column_count/?column=skill_set&model=resume
Accept: application/json

###

GET http://127.0.0.1:8000/charts/time_distribution/?column=russian_salary_to&model=vacancies&aggregates=avg
Accept: application/json

###

GET http://127.0.0.1:8000/charts/time_distribution/?column=skills&model=vacancies&aggregates=mode
Accept: application/json

###

GET http://127.0.0.1:8000/charts/time_distribution/?column=skill_set&model=resume&aggregates=mode&filters=skill_set!=SQL
Accept: application/json

###

GET http://127.0.0.1:8000/charts/time_distribution/?column=russian_salary&model=resume&aggregates=avg&filters=russian_salary<1000000
Accept: application/json

###

GET http://127.0.0.1:8000/charts/time_distribution/?column=russian_salary&model=resume&aggregates=avg
Accept: application/json

###

GET http://127.0.0.1:8000/charts/metric_distribution/?column=russian_salary&model=resume&number_range=10
Accept: application/json

###

GET http://127.0.0.1:8000/charts/metric_distribution/?column=russian_salary&model=resume&number_range=20&filters=russian_salary<1000000
Accept: application/json

###

GET http://127.0.0.1:8000/charts/metric_distribution/?column=russian_salary_from&model=vacancies&number_range=10
Accept: application/json

###

GET http://127.0.0.1:8000/charts/metric_column/?column=skills&model=vacancies&metric_column=russian_salary_to&aggregations=avg
Accept: application/json

###

GET http://127.0.0.1:8000/charts/metric_column/?column=experience&model=vacancies&metric_column=russian_salary_from&aggregations=avg
Accept: application/json

###

GET http://127.0.0.1:8000/charts/metric_column/?column=area&model=resume&metric_column=russian_salary&aggregations=avg
Accept: application/json

###