# Test your FastAPI endpoints

GET http://127.0.0.1:8000/vacancies/table/?filters=salary_to>=50000;min_experience<or:1~6;title=or:Аналитик данных~Data Scientist
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?group_by=address&aggregates=address:count&sort_by=address:count:desc
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?group_by=skills&aggregates=skills:count&sort_by=skills:count:desc
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?group_by=address&aggregates=salary_from:avg&sort_by=salary_from:avg:asc
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?group_by=address&aggregates=salary_from:avg,id:count&sort_by=salary_from:avg:desc
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?group_by=company_name&aggregates=company_name:count&sort_by=company_name:count:desc
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?specific_fields=skills&filters=skills==or:sql~excel
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?aggregates=salary_to:max
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?group_by=skills&sort_by=skills:desc
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?specific_fields=skills&not_null=skills
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?filters=skills==or:sql~excel
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?filters=salary_from=100000
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?aggregates=russian_salary_from:mode
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?specific_fields=salary_from&sort_by=salary_from:desc
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?group_by=skills,address&sort_by=skills:desc,address:asc
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?specific_fields=salary_to&not_null=salary_to&sort_by=salary_to:desc
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?group_by=skills,address&filters=address==москва&sort_by=address:desc
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?group_by=address&aggregates=id:count&having=id:count>10&sort_by=id:count:asc
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?group_by=company_name&aggregates=salary_from:avg,id:count&having=salary_from:avg>100000~id:count>1&sort_by=id:count:desc
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?specific_fields=russian_salary_to&sort_by=russian_salary_to:asc
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?group_by=skills&aggregates=skills:count&sort_by=skills:count:asc
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?specific_fields=skills&filters=skills==Pandas
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?specific_fields=skills&not_null=salary_from
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?specific_fields=skills&not_null=skills
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?specific_fields=russian_salary_from&filters=russian_salary_from>avg(russian_salary_from)
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?specific_fields=russian_salary_to&filters=russian_salary_to=100000
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?specific_fields=russian_salary_to&filters=russian_salary_to=100000
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?aggregates=russian_salary_to:avg
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?filters=russian_salary_to>157288.15234117646
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?filters=russian_salary_to>avg~russian_salary_to
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?aggregates=min_experience:avg,max_experience:avg
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?aggregates=min_experience:avg,max_experience:avg
Accept: application/json

###

GET http://127.0.0.1:8000/vacancies/table/?group_by=skills,address
Accept: application/json


