GET http://127.0.0.1:8000/charts/column-count/?column=address&model=vacancies
Accept: application/json

###

GET http://127.0.0.1:8000/charts/column-count/?column=skills&model=vacancies
Accept: application/json

###

GET http://127.0.0.1:8000/charts/column-count/?column=published_at&model=vacancies
Accept: application/json

###

GET http://127.0.0.1:8000/charts/column-count/?column=area&model=resume
Accept: application/json

###

GET http://127.0.0.1:8000/charts/column-count/?column=skill_set&model=resume
Accept: application/json

###