# Test your FastAPI endpoints

GET http://127.0.0.1:8000/resume/table/?filters=salary>=450000;total_experience<or:12~72;title==or:Аналитик данных~Data Scientist
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?group_by=area&aggregates=area:count&sort_by=area:count:desc
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?group_by=skill_set&aggregates=skill_set:count&sort_by=skill_set:count:desc
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?group_by=area&aggregates=salary:avg&sort_by=salary:avg:asc
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?group_by=area&aggregates=russian_salary:avg,id_resume:count&sort_by=russian_salary:avg:desc
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?group_by=experience&aggregates=experience:count&sort_by=experience:count:desc
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?specific_fields=skill_set&filters=skill_set==or:sql~excel
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?filters=russian_salary=max~russian_salary
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?group_by=skill_set&sort_by=skill_set:desc
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?specific_fields=skill_set&not_null=skill_set
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?filters=skill_set==or:sql~excel
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?filters=salary=100000
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?aggregates=russian_salary:mode
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?specific_fields=russian_salary&sort_by=russian_salary:desc
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?group_by=skill_set,area&sort_by=skill_set:desc,area:asc
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?specific_fields=salary&not_null=salary&sort_by=salary:desc
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?group_by=skill_set,area&filters=area==москва&sort_by=area:desc
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?group_by=area&aggregates=id_resume:count&having=id_resume:count>10&sort_by=id_resume:count:asc
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?group_by=experience&aggregates=salary:avg,id_resume:count&having=salary:avg>100000~id_resume:count>1&sort_by=id_resume:count:desc
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?specific_fields=russian_salary&sort_by=russian_salary:asc
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?group_by=skill_set&aggregates=skill_set:count&sort_by=skill_set:count:desc
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?specific_fields=skill_set&filters=skill_set==Pandas
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?specific_fields=skill_set&not_null=salary
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?specific_fields=skill_set&not_null=skill_set
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?group_by=area&aggregates=salary:avg&not_null=salary
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?specific_fields=russian_salary&filters=russian_salary>avg~russian_salary
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?specific_fields=russian_salary,url,experience,area
Accept: application/json


###

GET http://127.0.0.1:8000/resume/table/?specific_fields=russian_salary&filters=russian_salary=100000
Accept: application/json

###


GET http://127.0.0.1:8000/resume/table/?aggregates=russian_salary:avg
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?filters=russian_salary>157601.2011615888
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?filters=russian_salary>avg~russian_salary
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?aggregates=total_experience:avg
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?group_by=skill_set,area
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?offset=0&limit=8&group_by=currency&aggregates=employments:mode,currency:count
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?aggregates=created_at:max
Accept: application/json


###

GET http://127.0.0.1:8000/resume/table/?filters=created_at=or:mode~created_at
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?filters=currency=or:mode~currency
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?filters=skill_set=or:mode~skill_set
Accept: application/json

###

GET http://127.0.0.1:8000/resume/table/?aggregates=skill_set:mode
Accept: application/json

