default_vacancies_data = {
    'const': 1,
    'min_experience': 0,
    'type_of_employment_Другое': 0,
    'work_format_Полный день': 0,
    'skill_SQL': 0,
    'skill_MS Excel': 0,
    'skill_UML': 0,
    'skill_Работа с большим объемом информации': 0,
    'skill_SOAP': 0,
    'skill_Финансовый анализ': 0,
    'skill_Tableau': 0,
    'skill_DWH': 0,
    'skill_Hadoop': 0,
    'skill_Визуализация данных': 0,
    'skill_Clickhouse': 0,
    'skill_ERP-системы на базе 1С': 0,
    'skill_Системное мышление': 0,
    'skill_Системная интеграция': 0,
    'skill_Автоматизация процессов': 0,
    'skill_A/B тесты': 0,
    'skill_Оптимизация численности персонала': 0,
    'skill_Agile': 0,
    'skill_Разработка бизнес-требований': 0,
    'skill_1C: ERP': 0,
    'skill_1С: Зарплата и управление персоналом': 0,
    'skill_Kafka': 0,
    'address_other': 0,
    'address_Екатеринбург': 0,
    'address_Казань': 0,
    'address_Нижний Новгород': 0,
    'address_Новосибирск': 0,
    'address_Санкт-Петербург': 0
}

default_resume_data = {

}

selected_vacancies_skills = [
    'SQL',
    'MS Excel',
    'Системный анализ',
    'Python',
    'Бизнес-анализ',
    'UML',
    'Работа с большим объемом информации',
    'Power BI',
    'Разработка технических заданий',
    'MS SQL',
    'REST',
    'Постановка задач разработчикам',
    'MS PowerPoint',
    'PostgreSQL',
    'API',
    'SOAP',
    'Atlassian Jira',
    'XML',
    'Финансовый анализ',
    'Tableau',
    'DWH',
    'Формирование аналитической отчетности',
    'Atlassian Confluence',
    'JSON',
    'Английский язык',
    'REST API',
    'Hadoop',
    'Визуализация данных',
    'ETL',
    'Clickhouse',
    'Математическая статистика',
    'Big Data',
    'Power Query',
    'ERP-системы на базе 1С',
    'Прогнозирование',
    '1С: Предприятие 8',
    'Экономический анализ',
    'Системное мышление',
    'Финансовая отчетность',
    'Системная интеграция',
    'Git',
    'MS Visio',
    'Greenplum',
    'JSON API',
    '1С: Бухгалтерия',
    'ORACLE',
    'Автоматизация процессов',
    'A/B тесты',
    'Postman',
    '1С: Документооборот',
    'Apache Kafka',
    'Scrum',
    'Оптимизация численности персонала',
    'Agile',
    'Бюджетирование',
    'Разработка бизнес-требований',
    'Статистический анализ',
    'Use case',
    'Аналитика продаж',
    '1C: ERP',
    'Финансовое планирование',
    'Разработка функциональных требований',
    'Управление проектами',
    '1С: Зарплата и управление персоналом',
    'СУБД',
    'Swagger',
    'Финансовое моделирование',
    'Kafka'
]

vacancies_drop_columns = [
    'salary', 'type_of_employment_Полная занятость',
    'work_format_Удаленная работа', 'address_Москва'
]

resume_drop_columns = []

vacancies_y_column = "salary"

resume_y_column = ""